### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by spoorcc**
- Implemented [WaveDrom tutorial-page ](http://wavedrom.com/tutorial.html) using latex & WaveDromTikZ (only supported features)
- Added `make.sh` for  building example
- Added argparse for better argument handling
- Added standalone option, to generate standalone latex files
- Added output file optional argument
- Made robust for underscores in signal names
- Replaced tabs for spaces in python file

### CODE REVIEW

**Comment by mossblaser** [comment]
This is a fantastic contribution, thanks very much!

I noticed you changed the whitespace from tabs to three spaces. I don't mind the whitespace change since PEP-8 says tabs are evil etc however it would be great if you could use 4 spaces instead as this is what the PEP specifies and this matches Python in general.

Also, it would be good to mention in the TeXified tutorial a) that this is based on the original and b) give an example of use with a TeX file.

Thank you very much!

**Comment by spoorcc** [comment]
Good point! will update as requested

**Comment by spoorcc** [comment]
Rather a lot of pylint issues. What's your opinion on those?

```
Messages
--------

+------------------------------+------------+
|message id                    |occurrences |
+==============================+============+
|undefined-variable            |167         |
+------------------------------+------------+
|bad-continuation              |105         |
+------------------------------+------------+
|bad-whitespace                |68          |
+------------------------------+------------+
|bad-indentation               |62          |
+------------------------------+------------+
|line-too-long                 |3           |
+------------------------------+------------+
|unused-import                 |2           |
+------------------------------+------------+
|missing-docstring             |1           |
+------------------------------+------------+
|anomalous-backslash-in-string |1           |
+------------------------------+------------+



Global evaluation
-----------------
Your code has been rated at -60.86/10 (previous run: -60.86/10, +0.00)
```

**Comment by mossblaser** [comment]
I'm not sure, I don't know how best to interpret pylint's output
off-hand... In the past I've used flake-8 to do PEP-8 checks. I would not
be surprised if the code had quite a few violations, though, as it was
started at a point in time where I'd not yet learnt about PEP-8...

What is your opinion?

**Comment by spoorcc** [comment]
I will check if autopep8 can do the boring work for me :), and update what is sane to update.

**Comment by spoorcc** [comment]
Complies with flake8 except some line-to-long issues, but passes completly with:

    flake8 --max-line-length=120

**Comment by mossblaser** [comment]
Brilliant! Thanks very much!

Are you happy for me to merge this branch?

**Comment by spoorcc** [comment]
No problem, thank you for your tool :), helped me generating timing diagrams in my project http://spoorcc.github.io/realtimestagram/classrgb2hsv.html 

I tested purely using the examples in the example folder, they build. 
So from my perspective it is ready for merging.

**Comment by mossblaser** [comment]
Thank you so much for all your hard work. Awesome project by the way... I've been meaning to have some fun with some FPGA video processing! I may find your module very handy!

Happy new year (and sorry about my tardiness getting this merged!)

**Comment by spoorcc** [comment]
Haha, no problem! Thanks for the merge :).



FPGA is still learning project, so I can't vouch for the quality (yet),
but I can highly recommend GHDL (http://ghdl.readthedocs.io/).


Kind regards and Happy new year to you too!





On Mon, Jan 2, 2017, at 14:14, Jonathan Heathcote wrote:

> Thank you so much for all your hard work. Awesome project by the
> way... I've been meaning to have some fun with some FPGA video
> processing! I may find your module very handy!
> Happy new year (and sorry about my tardiness getting this merged!)



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/mossblaser/WaveDromTikZ/pull/1#issuecomment-269971000

**Pull request merged**
